### ISSUE TITLE
You should create a course that teaches all this!

### ISSUE THREAD

**Issue by Tylersuard** [AMAI-GmbH/AI-Expert-Roadmap#1]
This is amazing.  Thank you so much for creating it, and for presenting it in an easy-to-read format.  It would be really cool if you guys put together an entire course, with videos and everything, teaching all these concepts.  Just a suggestion.  Thank you again!

**Comment by danadalleh** [comment]
8bg6

**Comment by nasseralmohr12** [comment]
q

**Comment by nasseralmohr12** [comment]
#1

**Comment by rbohling** [comment]
I think that would be neat but asking a lot. Lol

**Comment by AziAli181** [comment]
Azo

**Comment by anonofal** [comment]
Good

**Comment by JStumpp** [comment]
@Tylersuard thanks for the suggestion, great idea, but yes, this is quite a lot. The roadmap links to resources that guide you into the right direction on where we think you can learn the information. We continually try to improve these resources, but at the moment we will not make a video course out of it.
