### ISSUE TITLE
Change the order of the EDA/Data wrangling section and add a few missing things to other parts 

### ISSUE THREAD

**Issue by Hellisotherpeople** [AMAI-GmbH/AI-Expert-Roadmap#12]
Hi all, this is a very nice chart but I believe that there should be slight modifications. 

**Data Science Roadmap**

"Dimensionality and Numerosity Reduction" is a large topic which would include the study of the "Principal Component Analysis" (PCA) algorithm as the very first thing you'd do. Yet PCA is seen as being the very final thing you look at in this section. I think you should put PCA right before Dimensionality Reduction or you should combine them. 

In the "Visualization section" you list some nice plotting libraries, but I think that [Bokeh](https://docs.bokeh.org/en/latest/index.html)  should be included here because it is a superior python plotting library (out of the box GPU/OpenGL support allowing for plotting millions of points, significantly more flexible interaction system) combined to the other options and is quickly becoming one of the important graphing libraries. 

Under "Data Sources" you may want to put "Data Mining and Web Scraping" or something along those lines since I think a Data Scientist should be able to get their own data rather than go on Kaggle or github awesome pages. 

**Machine Learning Roadmap**

Subsections under "Association Rule Learning" should be "Apriori algorithm", "ECLAT algorithm" and "Fp-trees" 

Subsections under Dimensionality Reduction should include (after PCA): "Random Projection", "NMF", "T-SNE", "UMAP" 

Subsections under Clustering should include (after Agglomerative): "OPTICS" and "HDBSCAN"

Subsections under "Classification" should include "Guassian Mixture Models" 

Logistic Regression is actually a binary classification algorithm, despite its name, so move it from regression to Classification

Moving Huggingface Transformers out from here and into the Deep Learning section.

**Deep Learning Roadmap**

Add a new section under "Architectures" called "Attention Mechanisms/Transformers"
Add a new section under Architectures called "NEAT/Evolving Architectures" 

**Big Data Engineer**

Add a new blue section under "Tools" for Dask, Numba, Onnx, and OpenVino

If it's really easy to generate these plots, I'm willing to make these changes and submit a PR. What are your thoughts on implementing some or all of these changes?

**Comment by JStumpp** [comment]
Thanks a lot for your suggestions, this is fixed in https://github.com/AMAI-GmbH/AI-Expert-Roadmap/pull/18
