### ISSUE TITLE
The Medium story linked to Denoising is deleted.

### ISSUE THREAD

**Issue by etanxing** [AMAI-GmbH/AI-Expert-Roadmap#20]
The Medium story linked to `Denoising` is deleted.

https://medium.com/analytics-vidhya/dealing-with-noisy-data-in-data-science-e177a4e32621

**Comment by rlirli** [comment]
Thanks @etanxing, I will look for a good replacement

**Comment by rlirli** [comment]
Here's a mirror for the original article:
https://yusout.com/2019/04/29/dealing-with-noisy-data-in-data-science/

Will put that into place

**Comment by rlirli** [comment]
Fixed this with PR #26
