### ISSUE TITLE
Fundamentals are not clear

### ISSUE THREAD

**Issue by aribanigar034** [AMAI-GmbH/AI-Expert-Roadmap#22]

**Comment by JStumpp** [comment]
Hi, thanks for the note, could you please clarify what exactly is not clear to you?

**Comment by Sam-code-stack** [comment]
fundamentals of which program

**Comment by rlirli** [comment]
@Sam-code-stack @aribanigar034 
The Fundamentals Block in the introduction is linking to the first roadmap called "[Fundamentals](https://github.com/AMAI-GmbH/AI-Expert-Roadmap#fundamentals)" just one image below.

**Comment by aribanigar034** [comment]
Okay, thank you
