### ISSUE TITLE
The best way to learn something is to build something

### ISSUE THREAD

**Issue by doroshroman** [AMAI-GmbH/AI-Expert-Roadmap#25]

**Comment by amitsindoliya** [comment]
Any suggestions on what to build?

**Comment by doroshroman** [comment]
It can be anything: 

- problems you want to solve or which bother you.
- something innovative.
- something that can be optimized by technology.

How can you find it?

- books(science fiction the best choice, but all good except self-help) to expand your mind and make you think better.

**Comment by joaojgabriel** [comment]
Or to simply realize the ultimate goal is to build things. Going through each fundamental in order feels really dull to me. What I think is a better approach, going **only partially** of skipping the fundamentals is to find interesting problems, scientific papers of people trying to solve this problem, or a part of it, and every time you stumble upon an idea, or a foreign term, you don't grasp, pulling out the roadmap to see what concept is that and find good resources, that fit your learning style, until you can explain it to anyone else. 

This way you cover a wider scope of knowledge, with unclear bounds (which is the default if you're out in the wild), exercise your "making sense of it" muscles, and connect a practical relevance to that concept you're learning, i.e. people trying to do what you find is really cool thought that using this concept as a tool, a building block, was essential to solve the problem at hand. Alway keeping in mind they could be wrong, and whole different path was better to do the same thing, but only when you're able to understand why they did what they did you can equip yourself in detail to advocate for a better way, and argument _why_ it would be better.  Then you look to expand your studies by the corners and start over.
