### ISSUE TITLE
AI doubt

### ISSUE THREAD

**Issue by js08** [AMAI-GmbH/AI-Expert-Roadmap#30]
Hi,

I am trying to apply AI and ML algorithms in my data, there are hundred thousand stores with competitors, where gas prices changes 15 minutes once. 
Assume in each city if I have my own gas station and how should I give my prices so that more customers come to my store.

Can we apply AI for my above logic

Thanks

**Comment by Sam-code-stack** [comment]
Yeah you can include AI

**Comment by js08** [comment]
@Sam-code-stack can you tell me how to solve it

**Comment by MohannadEhabBarakat** [comment]
@js08  I would solve it I'll try first linear regression or SVM. 
First:
try one model on all cities, see if it generalizes will. Then try to train it or retrain it on one city only and compare the results. 
seconde:
maybe I'll consider past prices too. So I'll try LSTM or something like that.

I'm not an expert yet, anyway these are my thoughts.

**Comment by Sam-code-stack** [comment]
Thanks

**Comment by js08** [comment]
@MohannadEhabBarakat @Sam-code-stack can you provide few working examples

**Comment by Sam-code-stack** [comment]
I can try my best

**Comment by gameatronist** [comment]
Buy a tesla and settle
