### ISSUE TITLE
Is this still relevant in 2023 

### ISSUE THREAD

**Issue by shxrif** [AMAI-GmbH/AI-Expert-Roadmap#80]
Thanks for ur reply!

**Comment by chanleeip** [comment]
Same doubt

**Comment by Skizzy-create** [comment]
The [AI Expert Roadmap](https://github.com/AMAI-GmbH/AI-Expert-Roadmap) is a great resource for anyone who is interested in learning about AI. It covers a wide range of topics, from the basics of machine learning to more advanced topics like deep learning. However, it is important to note that the field of AI is constantly evolving, so the roadmap may not be as up-to-date as some other resources.
```
**Pros:**

* **It covers a wide range of topics.**
* **It is well-organized and easy to follow.**
* **It provides links to additional resources.**

**Cons:**

* **It is not as up-to-date as some other resources.**
* **It can be a bit overwhelming for beginners.**
```
**Overall, the AI Expert Roadmap is a valuable resource for anyone who is interested in learning about AI.** However, it is important to keep in mind that it is not the only resource available, and it may not be as up-to-date as some other resources.

**If you are looking for a more up-to-date resource, I would recommend checking out the following:**

* [The AI Index](https://aiindex.stanford.edu/)
* [The Association for the Advancement of Artificial Intelligence](https://www.aaai.org/)
* [The Machine Learning Mastery Blog](https://machinelearningmastery.com/)
* [The OpenAI Blog](https://openai.com/blog/)
* [Google Machine Learning Crash Course](https://developers.google.com/machine-learning/intro-to-ml)

I hope this helps! Let me know if you have any other questions.

**Comment by shxrif** [comment]
@Skizzy-create thanks
