### ISSUE TITLE
Logistic Regression is Classification

### ISSUE THREAD

**Issue by TheHollidayInn** [AMAI-GmbH/AI-Expert-Roadmap#9]
Hey! I noticed you put logistic regression under regression. Despite its name, Logistic Regression is actually used for classification.

**Comment by JStumpp** [comment]
Hi @TheHollidayInn,

thanks, yes, it is correct, Logistic Regression is very often used for classification, but not only, which we would like to leave it in this category. 

[Wikipedia](https://en.m.wikipedia.org/wiki/Logistic_regression) explains it best:
> The logistic regression model itself simply models probability of output in terms of input and does not perform statistical classification (it is not a classifier), though it can be used to make a classifier, for instance by choosing a cutoff value and classifying inputs with probability greater than the cutoff as one class, below the cutoff as the other; this is a common way to make a binary classifier.

**Comment by AziAli181** [comment]
Azo
